### ISSUE TITLE
The userstyles cannot be installed in Stylus due to missing `@namespace` metadata

### ISSUE THREAD

**Issue by darkred** [kidonng/cherry#13]
Greetings, @kidonng 

I have noticed that your userstyles cannot be installed in Stylus (currently v1.5.17 in Chrome 89),
because they don't have the `@namespace` metadata.

I have made PR #12 for this 3 weeks ago.

I've made this issue, mostly in case the PR might have missed your attention *(you might haven't set GitHub to email you on pull requests)*, and clarify whether you are open to PRs.

**Comment by kidonng** [comment]
My sincere apologies for the delay! I get tons of notifications, some of them just stack up and I don't always have a chance to check back.

Contributions are certainly welcome! In fact the PR surprised me because this repository is mostly for myself and I don't expect many people would be interested. That said, if you spot any error in the future, I will respond as soon as possible.

**Comment by darkred** [comment]
Thank you, I'm glad!
